---
title: "Brick-Metrics"
subtitle: "Building Precision in Predicting USA Home Prices"
author: "-- MineCrafters"
title-slide-attributes:
  data-background-size: "None"
  data-background-opacity: "0.7"
  data-slide-number: none
format:
  revealjs:
    theme: league
    transition: slide
    background-transition: fade
  
editor: visual
execute:
  echo: false
  warning: false
  error: false
  message: false
  results: "hide"
---

```{r}
#| label: setup
#| include: false

# Plot theme
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 11))

# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7,        # 7" width
  fig.asp = 0.618,      # the golden ratio
  fig.retina = 3,       # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300             # higher dpi, sharper image
)
```

# <Question>

## <Title>

```{r}


```

```{r}


```

## <Title>

```{r}


```


## <Title>

```{r}

```

## <Title>

<Description>

## <Title>

```{r}

  
```

## Thank you !! {style="text-align: center"}
